# Setup
version_name: taskonomy
out_dir: "./exp/"

# Database
train_db_name: Taskonomy
val_db_name: Taskonomy
trBatch: 8
valBatch: 8
nworkers: 4

# Optimizer and scheduler
val_interval: 5000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000001
scheduler: poly

# Model
model: TransformerMTL_multi
backbone: vitT
head: mlp

TASKS:
   NAMES:
      - depth_euclidean
      - depth_zbuffer
      - edge_occlusion
      - edge_texture
      - keypoints2d
      - keypoints3d
      - normal
      - principal_curvature
      - reshading
      - segment_unsup2d
      - segment_unsup25d
