# Setup
version_name: nyud
out_dir: "./exp_sel/"

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 8
valBatch: 8
nworkers: 4
ignore_index: 255

# Optimizer and scheduler
val_interval: 5000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000001
lr_ts: True
scheduler: poly

# Model
model: TransformerMTL_multi
backbone: vitT
head: mlp

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_weights:
       semseg: 1.0
       depth: 1.0
       normals: 1.0
       edge: 1.0

loss_schema: affinity
group:
   group1:
   - semseg
   group2:
   - depth
   group3:
   - normals
   group4:
   - edge

affin_decay: 0.001
preference: None
prepos: 100