# Setup
version_name: taskonomy
out_dir: "./exp_sel/"

# Database
train_db_name: Taskonomy
val_db_name: Taskonomy
trBatch: 8
valBatch: 8
nworkers: 4

# Optimizer and scheduler
val_interval: 5000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.000001
scheduler: poly

# Model
model: TransformerMTL_multi
backbone: vitT
head: mlp

TASKS:
   NAMES:
      - depth_euclidean
      - depth_zbuffer
      - edge_occlusion
      - edge_texture
      - keypoints2d
      - keypoints3d
      - normal
      - principal_curvature
      - reshading
      - segment_unsup2d
      - segment_unsup25d

loss_schema: affinity
group:
   group1:
   - depth_euclidean
   group2:
   - depth_zbuffer
   group3:
   - edge_occlusion
   group4:
   - edge_texture
   group5:
   - keypoints2d
   group6:
   - keypoints3d
   group7:   
   - normal
   group8:   
   - principal_curvature
   group9:   
   - reshading
   group10:
   - segment_unsup2d
   group11:   
   - segment_unsup25d


affin_decay: 0.0001
preference: None
prepos: 100